<Project Sdk="Microsoft.NET.Sdk.Web">

  <!-- TargetFramework / Nullable / ImplicitUsings arrivano da Directory.Build.props -->

  <ItemGroup>
    <ProjectReference Include="..\GoCare.Application\GoCare.Application.csproj" />
    <ProjectReference Include="..\GoCare.Shared\GoCare.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

</Project>
