// <auto-generated />
using System;
using System.Collections.Generic;
using GoCare.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoCare.Application.Data.Business.Migrations
{
    [DbContext(typeof(BusinessDbContext))]
    [Migration("20260906213758_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoCare.Application.Models.Domain.Association", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvailabilityHours")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("availability_hours");

                    b.PrimitiveCollection<List<string>>("CoveredProvinces")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("covered_provinces");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Phones")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("phones");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_associations");

                    b.ToTable("associations", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.CareGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_care_groups");

                    b.HasIndex("CreatedBy", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_care_groups_created_by_name");

                    b.ToTable("care_groups", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.CareGroupMembership", b =>
                {
                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("admin_role");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InvitationEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("invitation_email");

                    b.Property<string>("InvitationToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("invitation_token");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("CareGroupId", "PersonId")
                        .HasName("pk_care_group_memberships");

                    b.HasIndex("InvitationToken")
                        .IsUnique()
                        .HasDatabaseName("ix_care_group_memberships_invitation_token");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_care_group_memberships_person_id");

                    b.ToTable("care_group_memberships", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.Companion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("relationship");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("surname");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.HasKey("Id")
                        .HasName("pk_companions");

                    b.HasIndex("TransportRequestId")
                        .HasDatabaseName("ix_companions_transport_request_id");

                    b.ToTable("companions", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.ContactAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("association_id");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.HasKey("Id")
                        .HasName("pk_contact_access_logs");

                    b.HasIndex("AssociationId")
                        .HasDatabaseName("ix_contact_access_logs_association_id");

                    b.HasIndex("TransportRequestId")
                        .HasDatabaseName("ix_contact_access_logs_transport_request_id");

                    b.ToTable("contact_access_logs", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.HasKey("Id")
                        .HasName("pk_device_tokens");

                    b.HasIndex("SubjectType", "SubjectId")
                        .HasDatabaseName("ix_device_tokens_subject_type_subject_id");

                    b.ToTable("device_tokens", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<int>("Channels")
                        .HasColumnType("integer")
                        .HasColumnName("channels");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("SubjectType", "SubjectId")
                        .HasDatabaseName("ix_notifications_subject_type_subject_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.SavedDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("place_name");

                    b.HasKey("Id")
                        .HasName("pk_saved_destinations");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_saved_destinations_person_id");

                    b.ToTable("saved_destinations", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.TransportModificationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("OutcomeMessage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("outcome_message");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.HasKey("Id")
                        .HasName("pk_transport_modification_requests");

                    b.HasIndex("TransportRequestId")
                        .HasDatabaseName("ix_transport_modification_requests_transport_request_id");

                    b.ToTable("transport_modification_requests", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.TransportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AssignedAssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_association_id");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_id");

                    b.Property<Guid?>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset>("DepartureDateHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_date_hour");

                    b.Property<DateTimeOffset?>("NotCoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_covered_at");

                    b.Property<string>("ReferenceEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reference_email");

                    b.Property<string>("ReferencePhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference_phone");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_status");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_id");

                    b.Property<DateTimeOffset?>("ReturnDateHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("return_date_hour");

                    b.Property<string>("TripDirection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_direction");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_transport_requests");

                    b.HasIndex("AssignedAssociationId")
                        .HasDatabaseName("ix_transport_requests_assigned_association_id");

                    b.HasIndex("BeneficiaryId")
                        .HasDatabaseName("ix_transport_requests_beneficiary_id");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_transport_requests_care_group_id");

                    b.HasIndex("RequestStatus")
                        .HasDatabaseName("ix_transport_requests_request_status");

                    b.HasIndex("RequestedById")
                        .HasDatabaseName("ix_transport_requests_requested_by_id");

                    b.ToTable("transport_requests", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.TransportRequestCandidate", b =>
                {
                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.Property<Guid>("AssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("association_id");

                    b.HasKey("TransportRequestId", "AssociationId")
                        .HasName("pk_transport_request_candidates");

                    b.HasIndex("AssociationId")
                        .HasDatabaseName("ix_transport_request_candidates_association_id");

                    b.ToTable("transport_request_candidates", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.TransportRequestRejection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("association_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.HasKey("Id")
                        .HasName("pk_transport_request_rejections");

                    b.HasIndex("AssociationId")
                        .HasDatabaseName("ix_transport_request_rejections_association_id");

                    b.HasIndex("TransportRequestId")
                        .HasDatabaseName("ix_transport_request_rejections_transport_request_id");

                    b.ToTable("transport_request_rejections", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.TripStatusTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MadeByAssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("made_by_association_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OperatorLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operator_label");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.HasKey("Id")
                        .HasName("pk_trip_status_transitions");

                    b.HasIndex("MadeByAssociationId")
                        .HasDatabaseName("ix_trip_status_transitions_made_by_association_id");

                    b.HasIndex("TransportRequestId", "OccurredAt")
                        .HasDatabaseName("ix_trip_status_transitions_transport_request_id_occurred_at");

                    b.ToTable("trip_status_transitions", (string)null);
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.Association", b =>
                {
                    b.OwnsOne("GoCare.Application.Models.Domain.Address", "Headquarter", b1 =>
                        {
                            b1.Property<Guid>("AssociationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("headquarter_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("headquarter_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("headquarter_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("headquarter_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("headquarter_street");

                            b1.HasKey("AssociationId");

                            b1.ToTable("associations");

                            b1.WithOwner()
                                .HasForeignKey("AssociationId")
                                .HasConstraintName("fk_associations_associations_id");
                        });

                    b.Navigation("Headquarter")
                        .IsRequired();
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.CareGroup", b =>
                {
                    b.HasOne("GoCare.Application.Models.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_groups_persons_created_by");
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.CareGroupMembership", b =>
                {
                    b.HasOne("GoCare.Application.Models.Domain.CareGroup", null)
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_group_memberships_care_groups_care_group_id");

                    b.HasOne("GoCare.Application.Models.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_group_memberships_persons_person_id");
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.Companion", b =>
                {
                    b.HasOne("GoCare.Application.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companions_transport_requests_transport_request_id");
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.ContactAccessLog", b =>
                {
                    b.HasOne("GoCare.Application.Models.Domain.Association", null)
                        .WithMany()
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contact_access_logs_associations_association_id");

                    b.HasOne("GoCare.Application.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contact_access_logs_transport_requests_transport_request_id");
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.Person", b =>
                {
                    b.OwnsOne("GoCare.Application.Models.Domain.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("home_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("home_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("home_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("home_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("home_address_street");

                            b1.HasKey("PersonId");

                            b1.ToTable("persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_id");
                        });

                    b.Navigation("HomeAddress");
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.SavedDestination", b =>
                {
                    b.HasOne("GoCare.Application.Models.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saved_destinations_persons_person_id");

                    b.OwnsOne("GoCare.Application.Models.Domain.Address", "SavedAddress", b1 =>
                        {
                            b1.Property<Guid>("SavedDestinationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("saved_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("saved_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("saved_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("saved_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("saved_address_street");

                            b1.HasKey("SavedDestinationId");

                            b1.ToTable("saved_destinations");

                            b1.WithOwner()
                                .HasForeignKey("SavedDestinationId")
                                .HasConstraintName("fk_saved_destinations_saved_destinations_id");
                        });

                    b.Navigation("SavedAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.TransportModificationRequest", b =>
                {
                    b.HasOne("GoCare.Application.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_modification_requests_transport_requests_transpor");
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.TransportRequest", b =>
                {
                    b.HasOne("GoCare.Application.Models.Domain.Association", null)
                        .WithMany()
                        .HasForeignKey("AssignedAssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transport_requests_associations_assigned_association_id");

                    b.HasOne("GoCare.Application.Models.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_requests_persons_beneficiary_id");

                    b.HasOne("GoCare.Application.Models.Domain.CareGroup", null)
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transport_requests_care_groups_care_group_id");

                    b.HasOne("GoCare.Application.Models.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_requests_persons_requested_by_id");

                    b.OwnsOne("GoCare.Application.Models.Domain.Address", "EndAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("end_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("end_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("end_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("end_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("end_address_street");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId")
                                .HasConstraintName("fk_transport_requests_transport_requests_id");
                        });

                    b.OwnsOne("GoCare.Application.Models.Domain.Address", "ReturnEndAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("return_end_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("return_end_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("return_end_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("return_end_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("return_end_address_street");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId")
                                .HasConstraintName("fk_transport_requests_transport_requests_id");
                        });

                    b.OwnsOne("GoCare.Application.Models.Domain.Address", "StartAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("start_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("start_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("start_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("start_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("start_address_street");

                            b1.HasKey("TransportRequestId");

                            b1.HasIndex("Province")
                                .HasDatabaseName("ix_transport_requests_start_address_province");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId")
                                .HasConstraintName("fk_transport_requests_transport_requests_id");
                        });

                    b.Navigation("EndAddress")
                        .IsRequired();

                    b.Navigation("ReturnEndAddress");

                    b.Navigation("StartAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.TransportRequestCandidate", b =>
                {
                    b.HasOne("GoCare.Application.Models.Domain.Association", null)
                        .WithMany()
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_request_candidates_associations_association_id");

                    b.HasOne("GoCare.Application.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_request_candidates_transport_requests_transport_r");
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.TransportRequestRejection", b =>
                {
                    b.HasOne("GoCare.Application.Models.Domain.Association", null)
                        .WithMany()
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_request_rejections_associations_association_id");

                    b.HasOne("GoCare.Application.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_request_rejections_transport_requests_transport_r");
                });

            modelBuilder.Entity("GoCare.Application.Models.Domain.TripStatusTransition", b =>
                {
                    b.HasOne("GoCare.Application.Models.Domain.Association", null)
                        .WithMany()
                        .HasForeignKey("MadeByAssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trip_status_transitions_associations_made_by_association_id");

                    b.HasOne("GoCare.Application.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trip_status_transitions_transport_requests_transport_reques");
                });
#pragma warning restore 612, 618
        }
    }
}
