// <auto-generated />
using System;
using System.Collections.Generic;
using GoCare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoCare.Data.Migrations
{
    [DbContext(typeof(GoCareDbContext))]
    partial class GoCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoCare.Models.Auth.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Auth.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_email_verification_tokens_account_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_email_verification_tokens_token");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Auth.FailedLoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.HasKey("Id")
                        .HasName("pk_failed_login_attempts");

                    b.HasIndex("Email", "AttemptedAt")
                        .HasDatabaseName("ix_failed_login_attempts_email_attempted_at");

                    b.ToTable("failed_login_attempts", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Auth.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_password_reset_tokens_account_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_refresh_tokens_account_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.AssistedPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_assisted_people");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_assisted_people_created_by");

                    b.ToTable("assisted_people", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.Association", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvailabilityHours")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("availability_hours");

                    b.PrimitiveCollection<List<string>>("CoveredProvinces")
                        .HasColumnType("text[]")
                        .HasColumnName("covered_provinces");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Phones")
                        .HasColumnType("text[]")
                        .HasColumnName("phones");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_associations");

                    b.ToTable("associations", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.CaregiverAssistedLink", b =>
                {
                    b.Property<Guid>("CaregiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("caregiver_id");

                    b.Property<Guid>("AssistedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assisted_person_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.HasKey("CaregiverId", "AssistedPersonId")
                        .HasName("pk_caregiver_assisted_links");

                    b.HasIndex("AssistedPersonId")
                        .HasDatabaseName("ix_caregiver_assisted_links_assisted_person_id");

                    b.ToTable("caregiver_assisted_links", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.Companion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("relationship");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("surname");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.HasKey("Id")
                        .HasName("pk_companions");

                    b.HasIndex("TransportRequestId")
                        .HasDatabaseName("ix_companions_transport_request_id");

                    b.ToTable("companions", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.ContactAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accessed_at");

                    b.Property<Guid>("AssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("association_id");

                    b.Property<string>("DataKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_kind");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.HasKey("Id")
                        .HasName("pk_contact_access_logs");

                    b.HasIndex("AssociationId")
                        .HasDatabaseName("ix_contact_access_logs_association_id");

                    b.HasIndex("TransportRequestId")
                        .HasDatabaseName("ix_contact_access_logs_transport_request_id");

                    b.ToTable("contact_access_logs", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("push_token");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.HasKey("Id")
                        .HasName("pk_device_tokens");

                    b.HasIndex("SubjectType", "SubjectId")
                        .HasDatabaseName("ix_device_tokens_subject_type_subject_id");

                    b.ToTable("device_tokens", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<int>("Channels")
                        .HasColumnType("integer")
                        .HasColumnName("channels");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("SubjectType", "SubjectId")
                        .HasDatabaseName("ix_notifications_subject_type_subject_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.SavedDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("place_name");

                    b.HasKey("Id")
                        .HasName("pk_saved_destinations");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_saved_destinations_person_id");

                    b.ToTable("saved_destinations", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.TransportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AssignedAssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_association_id");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("beneficiary_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset>("DepartureDateHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_date_hour");

                    b.Property<DateTimeOffset?>("NotCoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_covered_at");

                    b.Property<string>("ReferenceEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reference_email");

                    b.Property<string>("ReferencePhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference_phone");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_status");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_id");

                    b.Property<DateTimeOffset?>("ReturnDateHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("return_date_hour");

                    b.Property<string>("TripDirection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_direction");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_transport_requests");

                    b.HasIndex("AssignedAssociationId")
                        .HasDatabaseName("ix_transport_requests_assigned_association_id");

                    b.HasIndex("BeneficiaryId")
                        .HasDatabaseName("ix_transport_requests_beneficiary_id");

                    b.HasIndex("RequestStatus")
                        .HasDatabaseName("ix_transport_requests_request_status");

                    b.HasIndex("RequestedById")
                        .HasDatabaseName("ix_transport_requests_requested_by_id");

                    b.ToTable("transport_requests", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.TransportRequestCandidate", b =>
                {
                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.Property<Guid>("AssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("association_id");

                    b.HasKey("TransportRequestId", "AssociationId")
                        .HasName("pk_transport_request_candidates");

                    b.HasIndex("AssociationId")
                        .HasDatabaseName("ix_transport_request_candidates_association_id");

                    b.ToTable("transport_request_candidates", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.TransportRequestRejection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("association_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.HasKey("Id")
                        .HasName("pk_transport_request_rejections");

                    b.HasIndex("AssociationId")
                        .HasDatabaseName("ix_transport_request_rejections_association_id");

                    b.HasIndex("TransportRequestId")
                        .HasDatabaseName("ix_transport_request_rejections_transport_request_id");

                    b.ToTable("transport_request_rejections", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.TripOperatorLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.HasKey("Id")
                        .HasName("pk_trip_operator_links");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_trip_operator_links_token");

                    b.HasIndex("TransportRequestId")
                        .HasDatabaseName("ix_trip_operator_links_transport_request_id");

                    b.ToTable("trip_operator_links", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Domain.TripStatusTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MadeByAssociationId")
                        .HasColumnType("uuid")
                        .HasColumnName("made_by_association_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OperatorLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operator_label");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.HasKey("Id")
                        .HasName("pk_trip_status_transitions");

                    b.HasIndex("MadeByAssociationId")
                        .HasDatabaseName("ix_trip_status_transitions_made_by_association_id");

                    b.HasIndex("TransportRequestId", "OccurredAt")
                        .HasDatabaseName("ix_trip_status_transitions_transport_request_id_occurred_at");

                    b.ToTable("trip_status_transitions", (string)null);
                });

            modelBuilder.Entity("GoCare.Models.Auth.EmailVerificationToken", b =>
                {
                    b.HasOne("GoCare.Models.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_accounts_account_id");
                });

            modelBuilder.Entity("GoCare.Models.Auth.PasswordResetToken", b =>
                {
                    b.HasOne("GoCare.Models.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_accounts_account_id");
                });

            modelBuilder.Entity("GoCare.Models.Auth.RefreshToken", b =>
                {
                    b.HasOne("GoCare.Models.Auth.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_accounts_account_id");
                });

            modelBuilder.Entity("GoCare.Models.Domain.AssistedPerson", b =>
                {
                    b.HasOne("GoCare.Models.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assisted_people_persons_created_by");

                    b.OwnsOne("GoCare.Models.Domain.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<Guid>("AssistedPersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("home_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("home_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("home_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("home_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("home_address_street");

                            b1.HasKey("AssistedPersonId");

                            b1.ToTable("assisted_people");

                            b1.WithOwner()
                                .HasForeignKey("AssistedPersonId")
                                .HasConstraintName("fk_assisted_people_assisted_people_id");
                        });

                    b.Navigation("HomeAddress");
                });

            modelBuilder.Entity("GoCare.Models.Domain.Association", b =>
                {
                    b.HasOne("GoCare.Models.Auth.Account", null)
                        .WithOne()
                        .HasForeignKey("GoCare.Models.Domain.Association", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_associations_accounts_id");

                    b.OwnsOne("GoCare.Models.Domain.Address", "Headquarter", b1 =>
                        {
                            b1.Property<Guid>("AssociationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("headquarter_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("headquarter_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("headquarter_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("headquarter_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("headquarter_street");

                            b1.HasKey("AssociationId");

                            b1.ToTable("associations");

                            b1.WithOwner()
                                .HasForeignKey("AssociationId")
                                .HasConstraintName("fk_associations_associations_id");
                        });

                    b.Navigation("Headquarter");
                });

            modelBuilder.Entity("GoCare.Models.Domain.CaregiverAssistedLink", b =>
                {
                    b.HasOne("GoCare.Models.Domain.AssistedPerson", null)
                        .WithMany()
                        .HasForeignKey("AssistedPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caregiver_assisted_links_assisted_people_assisted_person_id");

                    b.HasOne("GoCare.Models.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caregiver_assisted_links_persons_caregiver_id");
                });

            modelBuilder.Entity("GoCare.Models.Domain.Companion", b =>
                {
                    b.HasOne("GoCare.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companions_transport_requests_transport_request_id");
                });

            modelBuilder.Entity("GoCare.Models.Domain.ContactAccessLog", b =>
                {
                    b.HasOne("GoCare.Models.Domain.Association", null)
                        .WithMany()
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contact_access_logs_associations_association_id");

                    b.HasOne("GoCare.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contact_access_logs_transport_requests_transport_request_id");
                });

            modelBuilder.Entity("GoCare.Models.Domain.Person", b =>
                {
                    b.HasOne("GoCare.Models.Auth.Account", null)
                        .WithOne()
                        .HasForeignKey("GoCare.Models.Domain.Person", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_persons_accounts_id");

                    b.OwnsOne("GoCare.Models.Domain.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("home_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("home_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("home_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("home_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("home_address_street");

                            b1.HasKey("PersonId");

                            b1.ToTable("persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_id");
                        });

                    b.Navigation("HomeAddress");
                });

            modelBuilder.Entity("GoCare.Models.Domain.SavedDestination", b =>
                {
                    b.HasOne("GoCare.Models.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saved_destinations_persons_person_id");

                    b.OwnsOne("GoCare.Models.Domain.Address", "SavedAddress", b1 =>
                        {
                            b1.Property<Guid>("SavedDestinationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("saved_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("saved_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("saved_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("saved_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("saved_address_street");

                            b1.HasKey("SavedDestinationId");

                            b1.ToTable("saved_destinations");

                            b1.WithOwner()
                                .HasForeignKey("SavedDestinationId")
                                .HasConstraintName("fk_saved_destinations_saved_destinations_id");
                        });

                    b.Navigation("SavedAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("GoCare.Models.Domain.TransportRequest", b =>
                {
                    b.HasOne("GoCare.Models.Domain.Association", null)
                        .WithMany()
                        .HasForeignKey("AssignedAssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transport_requests_associations_assigned_association_id");

                    b.HasOne("GoCare.Models.Domain.AssistedPerson", null)
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_requests_assisted_people_beneficiary_id");

                    b.HasOne("GoCare.Models.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_requests_persons_requested_by_id");

                    b.OwnsOne("GoCare.Models.Domain.Address", "EndAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("end_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("end_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("end_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("end_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("end_address_street");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId")
                                .HasConstraintName("fk_transport_requests_transport_requests_id");
                        });

                    b.OwnsOne("GoCare.Models.Domain.Address", "ReturnEndAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("return_end_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("return_end_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("return_end_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("return_end_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("return_end_address_street");

                            b1.HasKey("TransportRequestId");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId")
                                .HasConstraintName("fk_transport_requests_transport_requests_id");
                        });

                    b.OwnsOne("GoCare.Models.Domain.Address", "StartAddress", b1 =>
                        {
                            b1.Property<Guid>("TransportRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("start_address_city");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("start_address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("start_address_postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("start_address_province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("start_address_street");

                            b1.HasKey("TransportRequestId");

                            b1.HasIndex("Province")
                                .HasDatabaseName("ix_transport_requests_start_address_province");

                            b1.ToTable("transport_requests");

                            b1.WithOwner()
                                .HasForeignKey("TransportRequestId")
                                .HasConstraintName("fk_transport_requests_transport_requests_id");
                        });

                    b.Navigation("EndAddress")
                        .IsRequired();

                    b.Navigation("ReturnEndAddress");

                    b.Navigation("StartAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("GoCare.Models.Domain.TransportRequestCandidate", b =>
                {
                    b.HasOne("GoCare.Models.Domain.Association", null)
                        .WithMany()
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_request_candidates_associations_association_id");

                    b.HasOne("GoCare.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_request_candidates_transport_requests_transport_r");
                });

            modelBuilder.Entity("GoCare.Models.Domain.TransportRequestRejection", b =>
                {
                    b.HasOne("GoCare.Models.Domain.Association", null)
                        .WithMany()
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_request_rejections_associations_association_id");

                    b.HasOne("GoCare.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transport_request_rejections_transport_requests_transport_r");
                });

            modelBuilder.Entity("GoCare.Models.Domain.TripOperatorLink", b =>
                {
                    b.HasOne("GoCare.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trip_operator_links_transport_requests_transport_request_id");
                });

            modelBuilder.Entity("GoCare.Models.Domain.TripStatusTransition", b =>
                {
                    b.HasOne("GoCare.Models.Domain.Association", null)
                        .WithMany()
                        .HasForeignKey("MadeByAssociationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trip_status_transitions_associations_made_by_association_id");

                    b.HasOne("GoCare.Models.Domain.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trip_status_transitions_transport_requests_transport_reques");
                });
#pragma warning restore 612, 618
        }
    }
}
