<Project Sdk="Microsoft.NET.Sdk">

  <!-- TargetFramework / Nullable / ImplicitUsings arrivano da Directory.Build.props -->

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoCare.Shared\GoCare.Shared.csproj" />
  </ItemGroup>

</Project>
